import { SyntaxStyle } from "@opentui/core";

export const colors = {
  background: "#09090b",
  panel: "#111113",
  panelRaised: "#18181b",
  panelSoft: "#131316",
  border: "#27272a",
  borderStrong: "#3f3f46",
  text: "#e4e4e7",
  textBright: "#fafafa",
  muted: "#71717a",
  subtle: "#52525b",
  accent: "#60a5fa",
  cyan: "#22d3ee",
  green: "#4ade80",
  yellow: "#facc15",
  orange: "#fb923c",
  red: "#f87171",
  purple: "#c084fc",
  thinkingBg: "#11111a",
  toolReadBg: "#0b1720",
  toolWriteBg: "#0d1b13",
  toolShellBg: "#20170b",
  toolAgentBg: "#1b1023",
  toolOtherBg: "#10151d",
  diffBg: "#0d1117",
  selection: "#334155",
};

export const markdownStyle = SyntaxStyle.fromStyles({
  default: { fg: colors.text },
  text: { fg: colors.text },
  paragraph: { fg: colors.text },
  heading: { fg: colors.textBright, bold: true },
  "markup.heading": { fg: colors.textBright, bold: true },
  "markup.bold": { fg: colors.textBright, bold: true },
  "markup.italic": { fg: colors.text, italic: true },
  "markup.link": { fg: colors.cyan, underline: true },
  "markup.raw": { fg: colors.green },
  "markup.quote": { fg: colors.muted, italic: true },
  comment: { fg: colors.muted, italic: true },
  keyword: { fg: colors.purple },
  function: { fg: colors.accent },
  string: { fg: colors.green },
  number: { fg: colors.yellow },
  type: { fg: colors.cyan },
  operator: { fg: colors.purple },
  punctuation: { fg: colors.muted },
});

export const thinkingMarkdownStyle = SyntaxStyle.fromStyles({
  default: { fg: colors.muted },
  text: { fg: colors.muted },
  paragraph: { fg: colors.muted },
  heading: { fg: colors.purple, bold: true },
  "markup.heading": { fg: colors.purple, bold: true },
  "markup.bold": { fg: colors.textBright, bold: true },
  "markup.italic": { fg: colors.muted, italic: true },
  "markup.link": { fg: colors.cyan, underline: true },
  "markup.raw": { fg: colors.green },
  "markup.quote": { fg: colors.subtle, italic: true },
  comment: { fg: colors.subtle, italic: true },
  keyword: { fg: colors.purple },
  function: { fg: colors.accent },
  string: { fg: colors.green },
  number: { fg: colors.yellow },
  type: { fg: colors.cyan },
  operator: { fg: colors.purple },
  punctuation: { fg: colors.subtle },
});
